### ISSUE TITLE
ValueError while parsing raw data

### ISSUE THREAD

**Issue by en-you** [kijk2869/youtube-related#8]
```py
>>> import youtube_related
>>> 
>>> print(youtube_related.get('https://youtu.be/D1PvIWdJ8xo'))
[{'id': 'nM0xDI5R50E', 'title': '[MV] IU(아이유) _ BBIBBI(삐삐)', 'duration': 209}, {'id': 'vhteDkmcvB8', 'title': 'IU 아이유  | Best Songs Of IU 아이유 최고의 노래모음 - IU 최고의 노래 컬렉션 - IU Spring Playlist 🌸', 'duration': 8300}, {'id': 'o_nxIQTM_B0', 'title': "[IU] Blueming Live Clip (2019 IU Tour Concert 'Love, poem')", 'duration': 280}, {'id': 'd9IxdwEFk1c', 'title': '[MV] IU(아이유) _ Palette(팔레트) (Feat. G-DRAGON)', 'duration': 219}, {'id': 'JyXjf09-WNc', 'title': '✔아이유 IU 노래모음 6탄/112곡/7시간', 'duration': 25333}, {'id': 'TgOu00Mf3kI', 'title': '[MV] IU(아이유) _ eight(에잇) (Prod.&Feat. SUGA of BTS)', 'duration': 222}, {'id': 'Fyd1BiP6ipg', 'title': '[어디선가 들어본 노래 Playlist] 제목은 모르더라도, 한때 지겹도록 들었던', 'duration': 8610}, {'id': 'BzYnNdJhZQw', 'title': '[MV] IU(아이유) _ Through the Night(밤편지)', 'duration': 283}, {'id': 'yqtCGojXEpM', 'title': "IU(아이유) 'Blueming(블루밍)' 라이브🎤🎤(밴드ver.) | 가사 | 스페셜클립 | Special Clip | LYRICS [4K]", 'duration': 247}, {'id': 'f_iQRO5BdCM', 'title': 'IU(아이유) _ YOU&I(너랑나) MV', 'duration': 534}]
>>> print(youtube_related.get('https://youtu.be/D1PvIWdJ8xo'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shilu/.local/lib/python3.8/site-packages/youtube_related/client.py", line 9, in get
    Data = parse(RAW)
  File "/home/shilu/.local/lib/python3.8/site-packages/youtube_related/parser.py", line 20, in parse
    Data = __loadInitialData(RAW)
  File "/home/shilu/.local/lib/python3.8/site-packages/youtube_related/parser.py", line 11, in __loadInitialData
    raise ValueError
ValueError
```
If you request 30 times, you'll get ValueError about 1 ~ 2 times.

Using Python 3.8.5 with latest version of this library.

**Comment by en-you** [comment]
[response.txt](https://github.com/kijk2869/youtube-related/files/5472301/response.txt)
response.txt is what I get from the regex matching.
It seems to work after removing `;</script><script nonce="sqecxdqBdPTbWhCEAqNh7Q">if (window.ytcsi) {window.ytcsi.tick('pdr', null, '')` at the below.

**Comment by kijk2869** [comment]
I noticed that.

Sorry for the late response.
